
#
# USERS API
#


### GET ALL
GET http://localhost:5000/api/users

### GET ID
GET http://localhost:5000/api/users/5d6d5975d53d5c0438e32a4f

### POST
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Last First",
    "email": "user@uniandes.edu.co",
    "username": "user3"
}

### PATCH
PATCH http://localhost:5000/api/users/5d6d5975d53d5c0438e32a4f
Content-Type: application/json

{
    "name": "New Name"
}

### DELETE
DELETE http://localhost:5000/api/users/5d6d5975d53d5c0438e32a4f
