
#
# USUARIOS API
#


### GET ALL
GET http://localhost:5000/api/usuarios

### GET ID
GET http://localhost:5000/api/usuarios/5d6d5975d53d5c0438e32a4f

### POST
POST http://localhost:5000/api/usuarios
Content-Type: application/json

{
    "nombre": "Usuario Tester",
    "email": "tester@uniandes.edu.co",
    "nombreUsuario": "ElTester",
    "contrasenia": "easypass",
    "tipo": "cliente"
}

### PATCH
PATCH http://localhost:5000/api/usuarios/5d6d5975d53d5c0438e32a4f
Content-Type: application/json

{
    "nombre": "New Name"
}

### DELETE
DELETE http://localhost:5000/api/usuarios/5d87a842b7248b3458caceb4


### GET ALL pedidos from the user
GET http://localhost:5000/api/usuarios/5d6d5975d53d5c0438e32a4f/pedidos