
#
# USUARIOS API
#


### GET ALL
GET http://localhost:5000/api/usuarios

### GET ID
GET http://localhost:5000/api/usuarios/5d87c2b8e89720237c9b7fec

### POST
POST http://localhost:5000/api/usuarios
Content-Type: application/json

{
    "nombre": "Camilo Fernandez",
    "email": "camilo-92@example.com",
    "nombreUsuario": "ElTester",
    "contrasenia": "easypass",
    "tipo": "cliente"
}

### PATCH
PATCH http://localhost:5000/api/usuarios/5d87c2b8e89720237c9b7fec
Content-Type: application/json

{
    "nombre": "New Name"
}

### DELETE
DELETE http://localhost:5000/api/usuarios/5d87c2b8e89720237c9b7fec


### GET ALL pedidos from the user
GET http://localhost:5000/api/usuarios/5d87c2b8e89720237c9b7fec/pedidos